### ISSUE TITLE
Incorrect Date format

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#1]
![image](https://cloud.githubusercontent.com/assets/6502098/3867645/2996d0ce-2009-11e4-8e5e-9b481acfc54b.png)

![image](https://cloud.githubusercontent.com/assets/6502098/3867659/37968476-2009-11e4-89d1-dda0f54d605a.png)

![image](https://cloud.githubusercontent.com/assets/6502098/3867661/44de583e-2009-11e4-9dcd-c07e03338f5d.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Verified and Tested.
