### ISSUE TITLE
International dialling code drop-down box is incomplete

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#21]
![image](https://cloud.githubusercontent.com/assets/6502098/5331741/bee9bbb2-7e2f-11e4-8001-2435657e42b7.png)

**Comment by jctopo** [comment]
You can set it up in admin panel, country screen. Or you can get me the info and I upload it manually.

**Comment by pmt-it** [comment]
I have sent you an email in Excel

**Comment by jctopo** [comment]
Done

**Comment by pmt-it** [comment]
Verified
