### ISSUE TITLE
Default selection

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#22]
After selecting Destination country (China), the system should default the Receiver's country to be the same as Destination country (China), and after that, the dialling code

NOTE: We need to do more defaulting, we need to make the agent's life much easier!!!

![image](https://cloud.githubusercontent.com/assets/6502098/5331751/51665a72-7e30-11e4-9753-532c7fb92ff2.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Verified
