### ISSUE TITLE
Spelling 

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#28]
Please reword to "Transaction has been modified"

![image](https://cloud.githubusercontent.com/assets/6502098/5366233/2fef4014-7fea-11e4-99d3-16400934a7c6.png)

**Comment by jctopo** [comment]
Jjajajaaj thats the spanish transalation, remember we are multilanguage ... !!

**Comment by jctopo** [comment]
Fixed, not released

**Comment by pmt-it** [comment]
Verified
