### ISSUE TITLE
CEG Transaction screen - Rename Caption and pop-up screen

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#30]
1. Rename the Submit button to "Search"
2. Rename the Payment button to "View"
3. When click on the View button, please have it as a pop-up screen not opening a new tab

![image](https://cloud.githubusercontent.com/assets/6502098/5366357/fe822856-7fea-11e4-9001-855fc014d583.png)

**Comment by jctopo** [comment]
Fixed 1 and 2. Not released.

Item 3 will put on hold.

**Comment by pmt-it** [comment]
Item 1 and 2 verified. Will removed Fixed and Release label

**Comment by jctopo** [comment]
Please put a On Hold label ..!!

**Comment by pmt-it** [comment]
Verified
