### ISSUE TITLE
CEG Transaction screen - Marking Transaction As Processed and Upload UI

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#31]
Rename the "Marked As Processed" button to "Transaction Processed"

![image](https://cloud.githubusercontent.com/assets/6502098/5366450/b718299c-7feb-11e4-8d4d-030429082d4b.png)

**Comment by pmt-it** [comment]
After clicking on the "Transaction Processed" button (see below). Missing BACK button and still can change the image. 

![image](https://cloud.githubusercontent.com/assets/6502098/5423215/41736dc2-82a8-11e4-8fe1-e397f519b0c7.png)

**Comment by jctopo** [comment]
You can change the image on the client, but user is not able to post it to the server.

**Comment by pmt-it** [comment]
verified
