### ISSUE TITLE
Edit Customer screen

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#37]
1. Do we need this information?
2. We need to validate update SAVING the date entered are valid. That is, the Issue date is today or in the past. The Expriry date is tomorrow and beyond.
3. Button height is still different.

![image](https://cloud.githubusercontent.com/assets/6502098/5368894/1bd53948-8004-11e4-9a3d-36b4f65cf52c.png)

**Comment by jctopo** [comment]
1. Its the ID of the document, we need for reference.
2. Fixed
3. Fixed

**Comment by pmt-it** [comment]
Can you HIDE the information?

**Comment by pmt-it** [comment]
Verified Point 2 and 3. Awaiting for confirmation if we can HIDE the DocumentID.

**Comment by pmt-it** [comment]
Verified
