### ISSUE TITLE
Search Payout Locations reading from Config instead of Location tables 

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#4]
When you try to find the Location of Window Payment - you search by State and City on Create screen.
The system populate the STATE and CITY info from CONFIG_States and CONFIG_Cities but it should read from dbo.AGENT_Locations.

The config_\* tables has the complete dataset of a country states and cities. The available location is ONLY a subset of the Config_\* tables. So its really annoying that you select the states and cities and you find nothing....

**Comment by jctopo** [comment]
We going to address  this item in the new html5 version.

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Verified
