### ISSUE TITLE
Search customer on Search screen

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#41]
Search by 07722199096, yields 4 results as per screen shot below. Click on Money Penny & Resend.
![image](https://cloud.githubusercontent.com/assets/6502098/5423275/144d901c-82ac-11e4-975b-bf924b8ea5ef.png)

After the SEND screen got populated, I click on SEARCH button again and I found 1 record as per screen shot below. So far so good.

![image](https://cloud.githubusercontent.com/assets/6502098/5423276/2a4bfc1e-82ac-11e4-9b19-97cba7c9f7be.png)

Then I open another SEND screen, and search for Customer ID = 126. Obviously, one result came up. When the Send screen got populated with data, then I click on SEARCH button again and I got multiple results as per screen shot below. 

THE QUESTION I HAVE IS, WHAT IS THE SEARCH CRITERIA WHEN YOU CLICK ON THE "SEARCH" BUTTON

![image](https://cloud.githubusercontent.com/assets/6502098/5423280/6faf8186-82ac-11e4-9d52-f95da6938ed8.png)

Also, when you click on the SEARCH button again, and you choose Money Penny on the result, Money Penny's data get populated BUT the Customer ID is still = 126. 126 is James Bond. Money Penny's customer ID is 5. So we have a bug.

![image](https://cloud.githubusercontent.com/assets/6502098/5423479/69ed00a6-82b7-11e4-85dc-27b1c2a47a54.png)

**Comment by jctopo** [comment]
The customer ID refresh issues have been fixed.

**Comment by jctopo** [comment]
The search criteria on Search buttton retrieves data as follow,

Search by Customer ID + Search by First/Last Name + Search Criteria by Mobile/Phone number

it add the result of three search criterias.

**Comment by pmt-it** [comment]
No. This is not the correct approach. It should be one of the 3 search, and this is the order of preference. The system should first evaluate if the CUSTOMER ID is entered, if yes, then it should only use this parameter for the search.

If Customer ID is not entered, then the next preference is Search by First/Last Name
If First/Last Name are not entered, then the next preference is Search Criteria by Mobile/Phone number.

**Comment by pmt-it** [comment]
verified
