### ISSUE TITLE
error when clicking at the State combobox

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#5]
This error occurs occassionally and cannot reproduce every time. I think maybe because the values are NOT fully loaded hence you get the NULL messages.

![image](https://cloud.githubusercontent.com/assets/6502098/4319860/9b67f1fa-3f31-11e4-923b-32eaac7d531c.png)

**Comment by jctopo** [comment]
I have change the way we load those values, perhaps this error is fixed.

**Comment by pmt-it** [comment]
Verified
