### ISSUE TITLE
Logon issue when using CCB credential

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#6]
It think the error is related to what you have changed for Location search you implemented last week and with the condition that it need to have at least one location for AD and HD productions.

select \* from [dbo].[SYSTEM_ErrorLog] where ErrorID = 134

(p/s there are alot of errors on the table, do you look into it frequently?)

![image](https://cloud.githubusercontent.com/assets/6502098/4354213/b55b61f2-423b-11e4-8264-cb96955483e2.png)

**Comment by jctopo** [comment]
Fixed.

**Comment by pmt-it** [comment]
verified
