### ISSUE TITLE
Username MAX length not in sync with Admin Panel

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/POS#8]
The system (Admin Panel) allows you to create username 'steven.poh.manchester' (22 chars)
but the PMT POS only allow you to enter 21 chars

![image](https://cloud.githubusercontent.com/assets/6502098/4590268/b0ddc428-505d-11e4-8f4e-72abce83b8ae.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Fixed on 1.0.16.0
